name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        pod install
        swift build -v
    - name: Merge
      run: |
        git checkout origin/test
        git merge origin/master
        git push origin HEAD:test



        
    - name: Run tests
      run: swift test -v
   