name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        pod install
        swift build -v
    - name: Merge
      run: |
        git checkout test
        git merge master
    - name: Run tests
      run: swift test -v
